# Generated by Django 5.2.4 on 2025-07-08 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "book_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=30)),
                ("userid", models.DecimalField(decimal_places=0, max_digits=2)),
                ("busid", models.DecimalField(decimal_places=0, max_digits=2)),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.DecimalField(decimal_places=0, max_digits=2)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("B", "Booked"), ("C", "Cancelled"), ("P", "Pending")],
                        default="B",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.DecimalField(decimal_places=0, max_digits=2)),
                ("rem", models.DecimalField(decimal_places=0, max_digits=2)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="default", max_length=25),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="default", max_length=25),
                ),
                (
                    "payment_signature",
                    models.CharField(blank=True, default="default", max_length=128),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("RAZORPAY", "RAZORPAY"),
                            ("COD", "COD"),
                            ("ShopEase_WALLET", "ShopEase_WALLET"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
